# -*- coding: utf-8 -*-
"""Week 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQZt1e7Sd8SUlkIsZu8_pgLTE1pZC04E
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/sample_data/studentperformance_preprocessed.csv")
df

df.info()

df.head()

df.tail()

df.columns

df.describe()

df.isnull().sum()

df.shape

score_columns=['math score','reading score','writing score']

df[score_columns].head()

demographic_columns=['gender','race/ethnicity','parental level of education','lunch','test preparation course']
df[demographic_columns].head()

df['gender'].unique()

df['parental level of education'].unique()

df['lunch'].unique()

df['test preparation course'].unique()

"""Grouped Bar chart - Parental Education"""

parental_scores = df.groupby('parental level of education')[score_columns].mean()
parental_scores.plot(kind='bar',figsize=(12,6))
plt.title('Average Scores by Parental Level of Education')
plt.xlabel('Parental Level of Education')
plt.ylabel('Average Score')
plt.xticks(rotation=45)
plt.legend(title='Subject')
plt.tight_layout()
plt.show()

df["Average"] = df[["math score","reading score","writing score"]].mean(axis=1)

data = df.groupby(
    ["parental level of education", "lunch"]
)["Average"].mean().unstack()

data.plot(kind="bar", figsize=(10,6))

plt.xlabel("Parental Education")
plt.ylabel("Average Test Score")
plt.title("Average Test Scores by Parental Education and Lunch Type")
plt.xticks(rotation=45)
plt.legend(title="Lunch Type")
plt.tight_layout()
plt.show()

df["Average Score"] = df[["math score", "reading score",
                          "writing score"]].mean(axis=1)

df.boxplot(column="Average Score", by="test preparation course")

plt.title("Score Variance: Test Preparation")
plt.suptitle("")
plt.xlabel("Test Preparation")
plt.ylabel("Average Score")
plt.show()

plt.scatter(df["math score"], df["reading score"])
plt.xlabel("Math Score")
plt.ylabel("Reading Score")
plt.title("Math vs Reading Scores")
plt.show()

corr = df[["math score","reading score","writing score"]].corr()

plt.imshow(corr)
plt.colorbar()
plt.xticks(range(3), ["Math","Reading","Writing"])
plt.yticks(range(3), ["Math","Reading","Writing"])

for i in range(3):
    for j in range(3):
        plt.text(j, i, f"{corr.iloc[i,j]:.2f}", ha="center")

plt.title("Correlation Heatmap")
plt.show()

