# -*- coding: utf-8 -*-
"""Week 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJnJnp9S459nsW6BxIF9-z7NEAsoA4gR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/sample_data/archive (13).zip")
df

df.info()

df.head()

df.tail()

df.describe()

df.columns

df.isnull().sum()

score_columns=['math score','reading score','writing score']
df[score_columns].describe()

df[score_columns].mean()

df[score_columns].median()

df[score_columns].std()

df[score_columns].quantile([0.25,0.5,0.75])

df["Total Score"] = (df["math score"] +df["reading score"] +df["writing score"])
df

df["Percentage"]=(df["Total Score"]/300)*100

df[["Total Score","Percentage"]].head()

subjects = ["math score", "reading score", "writing score"]
for col in subjects:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    low = Q1 - 1.5 * IQR
    high = Q3 + 1.5 * IQR
    outliers = df[(df[col] < low) | (df[col] > high)]
    print("\n", col)
    print("Outliers:", len(outliers))
    print(outliers[[col]])