# -*- coding: utf-8 -*-
"""Week 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1swtgI5gZvSS5H1fRT-86ece68eIZhu0e
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/sample_data/healthcare_dataset (1).csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

df.columns

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])

df['Year_Month'] = df['Date of Admission'].dt.to_period('M')

monthly_admissions = df.groupby('Year_Month').size()
monthly_admissions.head()

peak_month = monthly_admissions.idxmax()
peak_admissions = monthly_admissions.max()
print("Peak Admission Month:", peak_month)
print("Number of Admissions:", peak_admissions)

billing_data = df.groupby(
    ['Medical Condition', 'Insurance Provider']
)['Billing Amount'].sum().unstack(fill_value=0)
billing_data.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6)
)
plt.title('Billing Amount by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Total Billing Amount')
plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)
plt.title('Billing Amount Distribution by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("Average Billing Amount by Medical Condition:")
print(df.groupby('Medical Condition')['Billing Amount'].mean())

print("\nAverage Billing Amount by Insurance Provider:")
print(df.groupby('Insurance Provider')['Billing Amount'].mean())

df['Admission Month']=df['Date of Admission'].dt.month
df['Admission Month']

monthly_admissions = df.groupby('Admission Month').size()
monthly_admissions

plt.figure(figsize=(12, 6))
monthly_admissions.plot(kind="line",marker="o")
plt.title('Monthly Admissions')
plt.xlabel('Month')
plt.ylabel('Number of Admissions')
plt.xticks(rotation=45)
plt.grid()
plt.show()

correlation_matrix = df[["Age","Billing Amount"]].corr()
print(correlation_matrix)

sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

"""The graphs provide a clear visual analysis of the healthcare dataset. The stacked bar chart compares total billing amounts across medical conditions and insurance providers. The violin plots show the distribution of billing amounts by medical condition and insurance provider. The line graph presents the monthly admission trend and highlights changes in the number of admissions over time. The correlation heatmap shows the relationship between the selected numerical variables. Overall, the visualizations make it easier to identify patterns, compare categories, and understand trends in the healthcare data."""