# -*- coding: utf-8 -*-
"""Week 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CiPKvdBX9ierUozEd499GsuDHs2zFKs1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

df = pd.read_excel("/content/sample_data/AAPL.xlsx")
df

print(df.head())

print(df.tail())

print(df.shape)

print(df.info())

print(df.describe())

print(df.isnull().sum())

df = df.dropna()

df = df.drop_duplicates()
df

df = df.sort_values("Date")

df["Daily_Delta"] = df["Close"] - df["Open"]

df["Daily_Return"] = (
    (df["Close"] - df["Open"]) / df["Open"]
) * 100

print(df[
    ["Date", "Open", "Close", "Daily_Delta", "Daily_Return"]
].head())

average = df[['Close', 'Open']].mean()
maximum = df[['Close', 'Open']].max()
minimum = df[['Close', 'Open']].min()

print("Average:", average)
print("Maximum:", maximum)
print("Minimum:", minimum)

threshold = 2 * average
print(threshold)

anomalous_days = df[df["Volume"] > volume_threshold]

print("\nAnomalous Trading Days:")
print(anomalous_days[ ["Date","Open","Close","Daily_Delta","Daily_Return","Volume"] ])

mean_return = df["Daily_Return"].mean()
variance_return = df["Daily_Return"].var()
std_return = df["Daily_Return"].std()

print("Mean Return:", mean_return)
print("Variance:", variance_return)
print("Standard Deviation:", std_return)

average_volume = df['Volume'].mean()
minimum_volume = df['Volume'].min()
maximum_volume = df['Volume'].max()

print(f"Average Trading Volume: {average_volume:,.2f}")
print(f"Minimum Trading Volume: {minimum_volume:,.2f}")
print(f"Maximum Trading Volume: {maximum_volume:,.2f}")

top_10_volume_days = df.sort_values(by='Volume', ascending=False).head(10)
display(top_10_volume_days[['Date', 'Volume', 'Open', 'Close']])